indent = 2
margin = 120
always_for_in = true
whitespace_typedefs = false
whitespace_ops_in_indices = true
remove_extra_newlines = false
import_to_using = false
pipe_to_function_call = false
short_to_long_function_def = false
always_use_return = false
whitespace_in_kwargs = true
annotate_untyped_fields_with_any = false
format_docstrings = false
align_struct_field = true
align_conditional = true
align_assignment = true
align_pair_arrow = true
conditional_to_if = false
normalize_line_endings = "auto"
align_matrix = false
trailing_comma = true