name = "Metatheory"
uuid = "e9d8d322-4543-424a-9be4-0cc815abe26c"
authors = ["Alessandro Cheli - 0x0f0f0f <sudo-woodo3@protonmail.com>"]
version = "0.5.0"

[deps]
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
AutoHashEquals = "0.2.0"
DataStructures = "0.18.9"
DocStringExtensions = "0.8"
Parameters = "0.12"
Reexport = "0.2, 1"
RuntimeGeneratedFunctions = "0.5.1"
TermInterface = "0.1.5"
TimerOutputs = "0.5"
julia = "1"

[extras]
Calculus = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Calculus", "Catlab"]
